---
- hosts: all
  tags:
    - configuration
  gather_facts: no
  tasks:
    - name: Creation of system value file of the target AS400 Server
      shell: sysval -p QABNORMSW QACGLVL QACTJOB QADLACTJ QADLSPLA QADLTOTJ QALWJOBITP QALWOBJRST QALWUSRDMN QASTLVL QATNPGM QAUDCTL QAUDENDACN QAUDFRCLVL QAUDLVL QAUDLVL2 QAUTOCFG QAUTORMT QAUTOSPRPT QAUTOVRT QBASACTLVL QBASPOOL QBOOKPATH QCCSID QCENTURY QCFGMSGQ QCHRID QCHRIDCTL QCMNARB QCMNRCYLMT QCNTRYID QCONSOLE QCRTAUT QCRTOBJAUD QCTLSBSD QCURSYM QDATE QDATETIME QDATFMT QDATSEP QDAY QDAYOFWEEK QDBFSTCCOL QDBRCVYWT QDECFMT QDEVNAMING QDEVRCYACN QDSCJOBITV QDSPSGNINF QDYNPTYADJ QDYNPTYSCD QENDJOBLMT QFRCCVNRST QHOUR QHSTLOGSIZ QIGC QIGCCDEFNT QIGCFNTSIZ QINACTMSGQ QINACTITV QIPLDATTIM QIPLSTS QIPLTYPE QJOBMSGQFL QJOBMSGQMX QJOBMSGQSZ QJOBMSGQTL QJOBSPLA QKBDBUF QKBDTYPE QLANGID QLEAPADJ QLIBLCKLVL QLMTDEVSSN QLMTSECOFR QLOCALE QLOGOUTPUT QMAXACTLVL QMAXJOB QMAXSGNACN QMAXSIGN QMAXSPLF QMCHPOOL QMINUTE QMLTTHDACN QMODEL QMONTH QPASTHRSVR QPFRADJ QPRBFTR QPRBHLDITV QPRCFEAT QPRCMLTTSK QPRTDEV QPRTKEYFMT QPRTTXT QPWDCHGBLK QPWDEXPITV QPWDEXPWRN QPWDLMTAJC QPWDLMTCHR QPWDLMTREP QPWDLVL QPWDMAXLEN QPWDMINLEN QPWDPOSDIF QPWDRQDDGT QPWDRQDDIF QPWDRULES QPWDVLDPGM QPWRDWNLMT QPWRRSTIPL QQRYDEGREE QQRYTIMLMT QRCLSPLSTG QRETSVRSEC QRMTIPL QRMTSIGN QRMTSRVATR QSAVACCPTH QSCANFS QSCANFSCTL QSCPFCONS QSECOND QSECURITY QSETJOBATR QSFWERRLOG QSHRMEMCTL QSPCENV QSPLFACN QSRLNBR QSRTSEQ QSRVDMP QSSLCSL QSSLCSLCTL QSSLPCL QSTGLOWACN QSTGLOWLMT QSTRPRTWTR QSTRUPPGM QSTSMSG QSVRAUTITV QSYSLIBL QTHDRSCADJ QTHDRSCAFN QTIMADJ QTIME QTIMSEP QTIMZON QTOTJOB QTSEPOOL QUPSDLYTIM QUPSMSGQ QUSEADPAUT QUSRLIBL QUTCOFFSET QVFYOBJRST QYEAR > /home/u_ans_ft/systems_value.txt
      register: echo
    - debug:
            msg: "{{ echo }}"

    - name: Copy file to Ansible host
      fetch:
            src: /home/u_ans_ft/systems_value.txt
            dest: /home/u_ans_ft/playbook/fetch_system_values/

    - name: Differentiate system value of the target AS400 Server to the value of the basis file
      shell: diff /home/u_ans_ft/playbook/fetch_system_values/{{ inventory_hostname }}/home/u_ans_ft/systems_value.txt /home/u_ans_ft/playbook/mother_file/file_basis.txt
      delegate_to: 127.0.0.1
      failed_when: "diff_result.rc > 1" 
      register: diff_result   

    - debug:
         msg: "The File are the same" 
      when: diff_result.rc == 0 
    - debug:
            msg: 'The file are not the same {{ diff_result.stdout_lines }}'
            #var: diff_result.stdout_lines      
      when: diff_result.rc != 0      
