---
- hosts: all
  gather_facts: no
  tasks:
  - ansible.windows.win_domain_membership:
      dns_domain_name: ssi.local
      hostname: ANSIBLE-SSI-MACHINE
      domain_admin_user: administrator@ssi.local
      domain_admin_password: Welcome@1
      domain_ou_path: "OU=Windows,OU=Servers,DC=ssi,DC=local"
      state: domain
    register: domain_state

  - ansible.windows.win_reboot:
    when: domain_state.reboot_required
