---
- name: Change Administrator Password
  hosts: all
  gather_facts: no
  tasks:
    - name: Set new password
      win_shell: |
        $securePassword = ConvertTo-SecureString -String "Password1" -AsPlainText -Force
        Set-LocalUser -Name "Administrator" -Password $securePassword
      become: yes
      become_user: Administrator
